import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import { useRecoilState } from 'recoil';
import { userState } from '../utils/atom';
import { UserData } from '../types/mainType';
import styles from '../styles/Home.module.css';
import { getData } from '../utils/getData';

const Home: NextPage = () => {
  const [userData, setUserData] = useRecoilState<UserData | null>(userState);

  useEffect(() => {
    (async () => {
      try {
        const data = await getData(`/pingpong/users`);
        setUserData(data); // slice로 0~2?만 리코일?
      } catch (e) {
        console.log(e);
      }
    })();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>42gg</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
    </div>
  );
};

export default Home;
