#!/bin/bash
branch_name=$(git symbolic-ref --short HEAD)

commit_msg_title=$(head -n 1 $1)
commit_msg_body=$(tail -n +2 $1)
contains_ggfe=$(echo $branch_name | grep -c "GGFE")

if [[ -n $branch_name ]] && [[ $contains_ggfe -eq 1 ]]; then
    echo "[Chores] $commit_msg_title" > $1
    if [[ -n $commit_msg_body ]]; then
        echo "$commit_msg_body" >> $1
    fi
else
    echo "Please check the branch name to ensure it contains 'GGFE'."
    exit 1
fi
